// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Straapp.Persistence;

#nullable disable

namespace Straapp.Persistence.Migrations
{
    [DbContext(typeof(StraappDbContext))]
    [Migration("20260928192903_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Straapp.Domain.Activities.Activity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("AchievementCount")
                        .HasColumnType("integer")
                        .HasColumnName("achievement_count");

                    b.Property<int>("AthleteCount")
                        .HasColumnType("integer")
                        .HasColumnName("athlete_count");

                    b.Property<long>("AthleteId")
                        .HasColumnType("bigint")
                        .HasColumnName("athlete_id");

                    b.Property<double?>("AverageCadence")
                        .HasColumnType("double precision")
                        .HasColumnName("average_cadence");

                    b.Property<double?>("AverageHeartrate")
                        .HasColumnType("double precision")
                        .HasColumnName("average_heartrate");

                    b.Property<double>("AverageSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("average_speed");

                    b.Property<double?>("AverageTemp")
                        .HasColumnType("double precision")
                        .HasColumnName("average_temp");

                    b.Property<double?>("AverageWatts")
                        .HasColumnType("double precision")
                        .HasColumnName("average_watts");

                    b.Property<double?>("Calories")
                        .HasColumnType("double precision")
                        .HasColumnName("calories");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count");

                    b.Property<bool>("Commute")
                        .HasColumnType("boolean")
                        .HasColumnName("commute");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<bool?>("DeviceWatts")
                        .HasColumnType("boolean")
                        .HasColumnName("device_watts");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision")
                        .HasColumnName("distance");

                    b.Property<int>("ElapsedTime")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_time");

                    b.Property<double?>("ElevHigh")
                        .HasColumnType("double precision")
                        .HasColumnName("elev_high");

                    b.Property<double?>("ElevLow")
                        .HasColumnType("double precision")
                        .HasColumnName("elev_low");

                    b.Property<double?>("EndLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("end_latitude");

                    b.Property<double?>("EndLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("end_longitude");

                    b.Property<string>("GearId")
                        .HasColumnType("text")
                        .HasColumnName("gear_id");

                    b.Property<double?>("Kilojoules")
                        .HasColumnType("double precision")
                        .HasColumnName("kilojoules");

                    b.Property<int>("KudosCount")
                        .HasColumnType("integer")
                        .HasColumnName("kudos_count");

                    b.Property<string>("LocationCountry")
                        .HasColumnType("text")
                        .HasColumnName("location_country");

                    b.Property<bool>("Manual")
                        .HasColumnType("boolean")
                        .HasColumnName("manual");

                    b.Property<double?>("MaxHeartrate")
                        .HasColumnType("double precision")
                        .HasColumnName("max_heartrate");

                    b.Property<double?>("MaxSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("max_speed");

                    b.Property<double?>("MaxWatts")
                        .HasColumnType("double precision")
                        .HasColumnName("max_watts");

                    b.Property<int>("MovingTime")
                        .HasColumnType("integer")
                        .HasColumnName("moving_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("integer")
                        .HasColumnName("photo_count");

                    b.Property<string>("Polyline")
                        .HasColumnType("text")
                        .HasColumnName("polyline");

                    b.Property<int>("PrCount")
                        .HasColumnType("integer")
                        .HasColumnName("pr_count");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean")
                        .HasColumnName("private");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("SportType")
                        .HasColumnType("text")
                        .HasColumnName("sport_type");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("StartDateLocal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date_local");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("start_latitude");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("start_longitude");

                    b.Property<double?>("SufferScore")
                        .HasColumnType("double precision")
                        .HasColumnName("suffer_score");

                    b.Property<string>("SummaryPolyline")
                        .HasColumnType("text")
                        .HasColumnName("summary_polyline");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<double>("TotalElevationGain")
                        .HasColumnType("double precision")
                        .HasColumnName("total_elevation_gain");

                    b.Property<bool>("Trainer")
                        .HasColumnType("boolean")
                        .HasColumnName("trainer");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<double?>("UtcOffset")
                        .HasColumnType("double precision")
                        .HasColumnName("utc_offset");

                    b.Property<string>("Visibility")
                        .HasColumnType("text")
                        .HasColumnName("visibility");

                    b.Property<double?>("WeightedAverageWatts")
                        .HasColumnType("double precision")
                        .HasColumnName("weighted_average_watts");

                    b.Property<int?>("WorkoutType")
                        .HasColumnType("integer")
                        .HasColumnName("workout_type");

                    b.HasKey("Id")
                        .HasName("pk_activities");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_activities_start_date");

                    b.HasIndex("AthleteId", "SportType")
                        .HasDatabaseName("ix_activities_athlete_id_sport_type");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("Straapp.Domain.Activities.ActivityComment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_id");

                    b.Property<long?>("AthleteId")
                        .HasColumnType("bigint")
                        .HasColumnName("athlete_id");

                    b.Property<string>("AthleteName")
                        .HasColumnType("text")
                        .HasColumnName("athlete_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_activity_comments");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_activity_comments_activity_id");

                    b.ToTable("activity_comments", (string)null);
                });

            modelBuilder.Entity("Straapp.Domain.Activities.ActivityEffort", b =>
                {
                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_id");

                    b.Property<string>("Kind")
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<double?>("AverageCadence")
                        .HasColumnType("double precision")
                        .HasColumnName("average_cadence");

                    b.Property<double?>("AverageHeartrate")
                        .HasColumnType("double precision")
                        .HasColumnName("average_heartrate");

                    b.Property<double?>("AverageWatts")
                        .HasColumnType("double precision")
                        .HasColumnName("average_watts");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision")
                        .HasColumnName("distance");

                    b.Property<int>("ElapsedTime")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_time");

                    b.Property<int?>("EndIndex")
                        .HasColumnType("integer")
                        .HasColumnName("end_index");

                    b.Property<int?>("KomRank")
                        .HasColumnType("integer")
                        .HasColumnName("kom_rank");

                    b.Property<double?>("MaxHeartrate")
                        .HasColumnType("double precision")
                        .HasColumnName("max_heartrate");

                    b.Property<int>("MovingTime")
                        .HasColumnType("integer")
                        .HasColumnName("moving_time");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PrRank")
                        .HasColumnType("integer")
                        .HasColumnName("pr_rank");

                    b.Property<long?>("SegmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("segment_id");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int?>("StartIndex")
                        .HasColumnType("integer")
                        .HasColumnName("start_index");

                    b.HasKey("ActivityId", "Kind", "Id")
                        .HasName("pk_activity_efforts");

                    b.HasIndex("SegmentId")
                        .HasDatabaseName("ix_activity_efforts_segment_id");

                    b.ToTable("activity_efforts", (string)null);
                });

            modelBuilder.Entity("Straapp.Domain.Activities.ActivityKudo", b =>
                {
                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Firstname")
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.HasKey("ActivityId", "Position")
                        .HasName("pk_activity_kudos");

                    b.ToTable("activity_kudos", (string)null);
                });

            modelBuilder.Entity("Straapp.Domain.Activities.ActivityLap", b =>
                {
                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_id");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<double?>("AverageCadence")
                        .HasColumnType("double precision")
                        .HasColumnName("average_cadence");

                    b.Property<double?>("AverageHeartrate")
                        .HasColumnType("double precision")
                        .HasColumnName("average_heartrate");

                    b.Property<double?>("AverageSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("average_speed");

                    b.Property<double?>("AverageWatts")
                        .HasColumnType("double precision")
                        .HasColumnName("average_watts");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision")
                        .HasColumnName("distance");

                    b.Property<int>("ElapsedTime")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_time");

                    b.Property<int?>("EndIndex")
                        .HasColumnType("integer")
                        .HasColumnName("end_index");

                    b.Property<int>("LapIndex")
                        .HasColumnType("integer")
                        .HasColumnName("lap_index");

                    b.Property<double?>("MaxHeartrate")
                        .HasColumnType("double precision")
                        .HasColumnName("max_heartrate");

                    b.Property<double?>("MaxSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("max_speed");

                    b.Property<int>("MovingTime")
                        .HasColumnType("integer")
                        .HasColumnName("moving_time");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PaceZone")
                        .HasColumnType("integer")
                        .HasColumnName("pace_zone");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int?>("StartIndex")
                        .HasColumnType("integer")
                        .HasColumnName("start_index");

                    b.Property<double?>("TotalElevationGain")
                        .HasColumnType("double precision")
                        .HasColumnName("total_elevation_gain");

                    b.HasKey("ActivityId", "Id")
                        .HasName("pk_activity_laps");

                    b.ToTable("activity_laps", (string)null);
                });

            modelBuilder.Entity("Straapp.Domain.Activities.ActivitySplit", b =>
                {
                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_id");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<double?>("AverageGradeAdjustedSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("average_grade_adjusted_speed");

                    b.Property<double?>("AverageHeartrate")
                        .HasColumnType("double precision")
                        .HasColumnName("average_heartrate");

                    b.Property<double>("AverageSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("average_speed");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision")
                        .HasColumnName("distance");

                    b.Property<int>("ElapsedTime")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_time");

                    b.Property<double?>("ElevationDifference")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation_difference");

                    b.Property<int>("MovingTime")
                        .HasColumnType("integer")
                        .HasColumnName("moving_time");

                    b.Property<int?>("PaceZone")
                        .HasColumnType("integer")
                        .HasColumnName("pace_zone");

                    b.HasKey("ActivityId", "Unit", "Index")
                        .HasName("pk_activity_splits");

                    b.ToTable("activity_splits", (string)null);
                });

            modelBuilder.Entity("Straapp.Domain.Activities.ActivityStreams", b =>
                {
                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_id");

                    b.PrimitiveCollection<double[]>("Altitude")
                        .HasColumnType("double precision[]")
                        .HasColumnName("altitude");

                    b.PrimitiveCollection<int[]>("Cadence")
                        .HasColumnType("integer[]")
                        .HasColumnName("cadence");

                    b.PrimitiveCollection<double[]>("Distance")
                        .HasColumnType("double precision[]")
                        .HasColumnName("distance");

                    b.PrimitiveCollection<double[]>("GradeSmooth")
                        .HasColumnType("double precision[]")
                        .HasColumnName("grade_smooth");

                    b.PrimitiveCollection<int[]>("Heartrate")
                        .HasColumnType("integer[]")
                        .HasColumnName("heartrate");

                    b.PrimitiveCollection<double[]>("Latitude")
                        .HasColumnType("double precision[]")
                        .HasColumnName("latitude");

                    b.PrimitiveCollection<double[]>("Longitude")
                        .HasColumnType("double precision[]")
                        .HasColumnName("longitude");

                    b.PrimitiveCollection<bool[]>("Moving")
                        .HasColumnType("boolean[]")
                        .HasColumnName("moving");

                    b.Property<int>("OriginalSize")
                        .HasColumnType("integer")
                        .HasColumnName("original_size");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<string>("SeriesType")
                        .HasColumnType("text")
                        .HasColumnName("series_type");

                    b.PrimitiveCollection<int[]>("Temp")
                        .HasColumnType("integer[]")
                        .HasColumnName("temp");

                    b.PrimitiveCollection<int[]>("Time")
                        .HasColumnType("integer[]")
                        .HasColumnName("time");

                    b.PrimitiveCollection<double[]>("VelocitySmooth")
                        .HasColumnType("double precision[]")
                        .HasColumnName("velocity_smooth");

                    b.PrimitiveCollection<int?[]>("Watts")
                        .HasColumnType("integer[]")
                        .HasColumnName("watts");

                    b.HasKey("ActivityId")
                        .HasName("pk_activity_streams");

                    b.ToTable("activity_streams", (string)null);
                });

            modelBuilder.Entity("Straapp.Domain.Activities.ActivityZone", b =>
                {
                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<bool?>("CustomZones")
                        .HasColumnType("boolean")
                        .HasColumnName("custom_zones");

                    b.PrimitiveCollection<double[]>("Max")
                        .IsRequired()
                        .HasColumnType("double precision[]")
                        .HasColumnName("max");

                    b.PrimitiveCollection<double[]>("Min")
                        .IsRequired()
                        .HasColumnType("double precision[]")
                        .HasColumnName("min");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.PrimitiveCollection<int[]>("Seconds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("seconds");

                    b.Property<bool?>("SensorBased")
                        .HasColumnType("boolean")
                        .HasColumnName("sensor_based");

                    b.HasKey("ActivityId", "Type")
                        .HasName("pk_activity_zones");

                    b.ToTable("activity_zones", (string)null);
                });

            modelBuilder.Entity("Straapp.Domain.Athletes.Athlete", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Firstname")
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<int?>("Ftp")
                        .HasColumnType("integer")
                        .HasColumnName("ftp");

                    b.Property<string>("Lastname")
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("MeasurementPreference")
                        .HasColumnType("text")
                        .HasColumnName("measurement_preference");

                    b.Property<bool>("Premium")
                        .HasColumnType("boolean")
                        .HasColumnName("premium");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_url");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("Sex")
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.Property<string>("ZonesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("zones_json");

                    b.HasKey("Id")
                        .HasName("pk_athletes");

                    b.ToTable("athletes", (string)null);
                });

            modelBuilder.Entity("Straapp.Domain.Athletes.Gear", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<long>("AthleteId")
                        .HasColumnType("bigint")
                        .HasColumnName("athlete_id");

                    b.Property<string>("BrandName")
                        .HasColumnType("text")
                        .HasColumnName("brand_name");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision")
                        .HasColumnName("distance");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("ModelName")
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<bool>("Primary")
                        .HasColumnType("boolean")
                        .HasColumnName("primary");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<bool>("Retired")
                        .HasColumnType("boolean")
                        .HasColumnName("retired");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Id")
                        .HasName("pk_gear");

                    b.HasIndex("AthleteId")
                        .HasDatabaseName("ix_gear_athlete_id");

                    b.ToTable("gear", (string)null);
                });

            modelBuilder.Entity("Straapp.Domain.Activities.ActivityComment", b =>
                {
                    b.HasOne("Straapp.Domain.Activities.Activity", null)
                        .WithMany("Comments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_comments_activities_activity_id");
                });

            modelBuilder.Entity("Straapp.Domain.Activities.ActivityEffort", b =>
                {
                    b.HasOne("Straapp.Domain.Activities.Activity", null)
                        .WithMany("Efforts")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_efforts_activities_activity_id");
                });

            modelBuilder.Entity("Straapp.Domain.Activities.ActivityKudo", b =>
                {
                    b.HasOne("Straapp.Domain.Activities.Activity", null)
                        .WithMany("Kudos")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_kudos_activities_activity_id");
                });

            modelBuilder.Entity("Straapp.Domain.Activities.ActivityLap", b =>
                {
                    b.HasOne("Straapp.Domain.Activities.Activity", null)
                        .WithMany("Laps")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_laps_activities_activity_id");
                });

            modelBuilder.Entity("Straapp.Domain.Activities.ActivitySplit", b =>
                {
                    b.HasOne("Straapp.Domain.Activities.Activity", null)
                        .WithMany("Splits")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_splits_activities_activity_id");
                });

            modelBuilder.Entity("Straapp.Domain.Activities.ActivityStreams", b =>
                {
                    b.HasOne("Straapp.Domain.Activities.Activity", null)
                        .WithOne("Streams")
                        .HasForeignKey("Straapp.Domain.Activities.ActivityStreams", "ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_streams_activities_activity_id");
                });

            modelBuilder.Entity("Straapp.Domain.Activities.ActivityZone", b =>
                {
                    b.HasOne("Straapp.Domain.Activities.Activity", null)
                        .WithMany("Zones")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_zones_activities_activity_id");
                });

            modelBuilder.Entity("Straapp.Domain.Activities.Activity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Efforts");

                    b.Navigation("Kudos");

                    b.Navigation("Laps");

                    b.Navigation("Splits");

                    b.Navigation("Streams");

                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
